buildlib: make better CC and CFLAGS guesses
Try gcc, clang and cc before failing to find a default compiler.
If CFLAGS is not set only use -O2 for gcc and clang otherwise -O.

diff --git a/buildlib b/buildlib
--- a/buildlib
+++ b/buildlib
@@ -1,11 +1,31 @@
 #!/bin/sh
-: ${CC:=gcc}
+if [ -z "$CC" ]; then
+  if command -v gcc > /dev/null; then
+    CC=gcc
+  elif command -v clang > /dev/null; then
+    CC=clang
+  elif command -v cc > /dev/null; then
+    CC=cc
+  else
+    echo "Could not guess name of compiler, please set CC" >&2
+    exit 2
+  fi
+fi
 echo "CC=$CC"
 : ${AR:=ar}
 echo "AR=$AR"
 : ${RANLIB:=ranlib}
 echo "RANLIB=$RANLIB"
-: ${CFLAGS:=-O2}
+if [ "${CFLAGS+set}" != "set" ]; then
+  case "$CC" in
+    *gcc*|*clang*)
+      CFLAGS=-O2
+      ;;
+    *)
+      CFLAGS=-O
+      ;;
+  esac
+fi
 echo "CFLAGS=$CFLAGS"
 set -v
 LIB=libBlocksRuntime.a
