support shared library builds
Although use of the static library is recommended, support building
a shared library as well with the optional `-shared` option.

By default install both if they exist, but allow a single `-shared`
or `-static` to be passed to the installlib script to limit the
installation to just one or the other.

Signed-off-by: Kyle J. McKay <mackyle@gmail.com>

diff --git a/installlib b/installlib
--- a/installlib
+++ b/installlib
@@ -9,6 +9,7 @@ set -e
 
 HEADER=BlocksRuntime/Block.h
 LIB=libBlocksRuntime.a
+SHLIB=
 
 docmd()
 {
@@ -24,17 +25,52 @@ if [ ! -r $HEADER ]; then
 	echo "Cannot find $HEADER, aborting!"
 	exit 1
 fi
-if [ ! -r $LIB ]; then
-	echo "Cannot find $LIB, did you run buildlib or buildlib-osx?"
-	exit 1
-fi
 dryrun=
 if [ "$1" = '-n' ] || [ "$1" = '--dry-run' ]; then
 	dryrun=1
 	shift
 fi
+static=1
+shared=1
+case "$1" in
+	"-static"|"--static")
+		shift
+		shared=
+		;;
+	"-shared"|"--shared")
+		shift
+		static=
+		;;
+esac
 if [ "$#" != 0 ]; then
-	echo "Usage: [prefix=prefixdir] $0 [-n | --dry-run]"
+	echo "Usage: [prefix=prefixdir] $0 [-n | --dry-run] [-shared | -static]"
+	exit 1
+fi
+if [ -n "$shared" ]; then
+	UNAME_S="$(uname -s 2>/dev/null)" || :
+	case "$UNAME_S" in
+		Darwin)
+			SHLIB="${LIB%.a}.dylib"
+			SHLIBMODE=755
+			;;
+		*)
+			SHLIB="${LIB%.a}.so"
+			SHLIBMODE=644
+			;;
+	esac
+	if [ -n "$static" ]; then
+		# ignore a missing shared library
+		[ -e "$SHLIB" ] || SHLIB=
+	else
+		LIB=
+	fi
+fi
+if [ -n "$LIB" ] && [ ! -r "$LIB" ]; then
+	echo "Cannot find $LIB, did you run \`buildlib\` or \`buildlib-osx\`?"
+	exit 1
+fi
+if [ -n "$SHLIB" ] && [ ! -r "$SHLIB" ]; then
+	echo "Cannot find $SHLIB, did you run \`buildlib -shared\` or \`buildlib-osx -shared\`?"
 	exit 1
 fi
 
@@ -53,4 +89,7 @@ if [ -z "$DESTDIR" -a -z "$dryrun" -a "$myid" != 0 ]; then
 fi
 docmd "install -d "$DESTDIR"$includedir "$DESTDIR"$libdir"
 docmd "install -m 644 $HEADER "$DESTDIR"$includedir/"
+[ -z "$LIB" ] ||
 docmd "install -m 644 $LIB "$DESTDIR"$libdir/"
+[ -z "$SHLIB" ] ||
+docmd "install -m $SHLIBMODE $SHLIB "$DESTDIR"$libdir/"
