installlib: minor cleanup
Some whitespace cleanup, if reduction and set -e.

Signed-off-by: Kyle J. McKay <mackyle@gmail.com>

diff --git a/installlib b/installlib
--- a/installlib
+++ b/installlib
@@ -1,44 +1,45 @@
 #!/bin/sh
 
-: ${prefix:=/usr/local}
-: ${includedir:=$prefix/include}
-: ${libdir:=$prefix/lib}
-: ${DESTDIR:=}
+set -e
+
+: "${prefix:=/usr/local}"
+: "${includedir:=$prefix/include}"
+: "${libdir:=$prefix/lib}"
+: "${DESTDIR:=}"
 
 HEADER=BlocksRuntime/Block.h
 LIB=libBlocksRuntime.a
 
 docmd()
 {
-  echo "$*"
-  if [ -z "$dryrun" ]; then eval "$*"; fi
+	echo "$*"
+	if [ -z "$dryrun" ]; then eval "$*"; fi
 }
 
 if ! myid="$(id -u)"; then
-  echo "Cannot run id, aborting!"
-  exit 1
+	echo "Cannot run id, aborting!"
+	exit 1
 fi
 if [ ! -r $HEADER ]; then
-  echo "Cannot find $HEADER, aborting!"
-  exit 1
+	echo "Cannot find $HEADER, aborting!"
+	exit 1
 fi
 if [ ! -r $LIB ]; then
-  echo "Cannot find $LIB, did you run buildlib or buildlib-osx?"
-  exit 1
+	echo "Cannot find $LIB, did you run buildlib or buildlib-osx?"
+	exit 1
 fi
 dryrun=
 if [ "$1" = '-n' ] || [ "$1" = '--dry-run' ]; then
-  dryrun=1
-  shift
+	dryrun=1
+	shift
 fi
 if [ "$#" != 0 ]; then
-  echo "Usage: [prefix=prefixdir] $0 [-n | --dry-run]"
-  exit 1
+	echo "Usage: [prefix=prefixdir] $0 [-n | --dry-run]"
+	exit 1
 fi
 
-if [ -n "$DESTDIR" ]; then
+[ -z "$DESTDIR" ] ||
 echo "Destination Root(\$DESTDIR):     $DESTDIR (default is \"\")"
-fi
 echo "Install Prefix(\$prefix):        $prefix (default is /usr/local)"
 echo "Include Directory(\$includedir): $includedir (default is \$prefix/include)"
 echo "Library Directory(\$libdir):     $libdir (default is \$prefix/lib)"
@@ -46,9 +47,9 @@ echo "(use prefix=prefixdir $0 [or similar] to change)"
 echo ''
 
 if [ -z "$DESTDIR" -a -z "$dryrun" -a "$myid" != 0 ]; then
-  echo "Must be root to install, use sudo $0"
-  echo "(Or try using the --dry-run option)"
-  exit 1
+	echo "Must be root to install, use sudo $0"
+	echo "(Or try using the --dry-run option)"
+	exit 1
 fi
 docmd "install -d "$DESTDIR"$includedir "$DESTDIR"$libdir"
 docmd "install -m 644 $HEADER "$DESTDIR"$includedir/"
